# Generated by Django 2.1.3 on 2018-11-24 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='emails',
            new_name='email',
        ),
    ]
