# Generated by Django 2.1.3 on 2018-11-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20181124_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=30, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail para contato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscricaoestadual',
            field=models.CharField(max_length=30, verbose_name='Inscrição Estadual'),
        ),
    ]
