# Generated by Django 2.1.3 on 2018-11-26 04:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orcamento',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
