# Generated by Django 2.1.3 on 2018-11-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20181126_0207'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orcamento',
            managers=[
            ],
        ),
    ]
